#!/bin/bash

##################################################################################
#####     Root Stack Variables                          #####
##################################################################################
#   Setting up variables
templateFile="template.yaml"
bucketName="aws-sam-stacks"
S3Prefix=""
outputTemplateFile="packaged.yaml"
useJSON=$false
forceUpload=$true
stackName="TEST"
##################################################################################
#####     Root Stack Pre-Porcessing                     #####
##################################################################################
#   Uploading MySQL script from Nested RDS Stack
aws s3 cp ./RDS-Aurora-Serverless/DBInfo/Schema_Script.sql s3://aws-sam-stacks/DBInfo/
##################################################################################
#####     Packaging RDS-Aurora-Serverless Stack        #####
##################################################################################
aws cloudformation package \
--template-file "./RDS-Aurora-Serverless/template.yaml" \
--s3-bucket $bucketName \
--output-template-file "./RDS-Aurora-Serverless/packaged.yaml" \
# --use-json $useJSON \
# --force-upload $forceUpload \
# --debug
# --s3-prefix "$S3Prefix/package" \
# --kms-key-id  \
# --metadata  \
##################################################################################
#####     Packaging Auth Stack                          #####
##################################################################################
aws cloudformation package \
--template-file "./Auth/template.yaml" \
--s3-bucket $bucketName \
--output-template-file "./Auth/packaged.yaml" \
# --use-json $useJSON \
# --force-upload $forceUpload \
# --debug
# --s3-prefix "$S3Prefix/package" \
# --kms-key-id  \
# --metadata  \
##################################################################################
#####     Packaging Root Stack          #####
##################################################################################
aws cloudformation package \
--template-file $templateFile \
--s3-bucket $bucketName \
--output-template-file $outputTemplateFile \
# --use-json $useJSON \
# --force-upload $forceUpload \
# --debug
# --s3-prefix "$S3Prefix/package" \
# --kms-key-id  \
# --metadata  \
##################################################################################
#####     Deploying Root Stack          #####
##################################################################################
#   Deploying RDS Stack
aws cloudformation deploy \
--template-file $outputTemplateFile \
--stack-name $stackName \
--s3-bucket $bucketName \
--force-upload $true \
--capabilities CAPABILITY_NAMED_IAM
# --s3-prefix "$S3Prefix/deploy" \
# --kms-key-id  \

##################################################################################
#   You package all the nested stacks and then refer to the output template (packaged.yaml)
#   The package.yaml file will contain the S3 bucket location of the code
#   For lambda functions that are in the nested function make sure they have their own seperate
#   folder

