AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Voltic Labs sample root stack.

  '
Resources:
  ElasticSearch:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ElasticsearchLayer:
          Fn::GetAtt:
          - LambdaLayers
          - Outputs.ElasticsearchLambdaLayer
      Tags:
      - Key: ElasticSearchStackKey
        Value: ElasticSearchStackValue
      TemplateURL: https://s3.amazonaws.com/aws-sam-stacks/0ddaa09f8f3a50665418a7b199acb27f.template
      TimeoutInMinutes: 15
  LambdaLayers:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.amazonaws.com/aws-sam-stacks/86f9aa8ec6782936dde77db3380b49e0.template
      TimeoutInMinutes: 15
