#!/bin/bash

sam build --debug

sam package --output-template-file packaged.yaml --s3-bucket aws-sam-stacks 

sam deploy --template-file packaged.yaml --stack-name liveworkStackB --capabilities CAPABILITY_NAMED_IAM
