#!/bin/bash

# sam build --debug
# sam package --output-template-file packaged.yaml --s3-bucket aws-sam-stacks 
# sam deploy --template-file packaged.yaml --stack-name liveworksABC --capabilities CAPABILITY_NAMED_IAM

aws cloudformation package --template-file template.yaml --s3-bucket aws-sam-stacks --output-template-file packaged.yaml --debug
aws cloudformation deploy --template-file packaged.yaml --stack-name SAFI --capabilities CAPABILITY_NAMED_IAM
